const sampledata = [
  {
    id: 1,
    Rut: 15957386,
    Nombres: "Jonathan Antonio",
    ApellidoPaterno: "Hernandez",
    ApellidoMaterno: "Miranda",
    FechaNacimiento: "1984-09-13",
    NumeroContacto: 978778829,
    EstadoCivil: "Casado",
    email: "leslie.alexander@example.com",
    role: "Co-Founder / CEO",
    EquipoTrabajo: "Diaconos",
    RedAsignada: "Ruah",
    EstadoIglesia: "Activo",
    GrupoIglesia: "Matrimonios Jóvenes",
    EstadoActualizacion: "Actualizado",
    imageUrl:
      "https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80",
    lastSeen: "✅",
    lastSeenDateTime: "2023-01-23T13:23Z",
    LugarOrigen: "IverCentral",
    // InfoIglesia: {
    //   Directorio: "Secretario",
    //   RedAsignada: "Ruah",
    //   NivelLiderazgo: "Diacono",
    //   EquipoTrabajo: "Diaconos",
    //   GrupoAsignado: "Iver Varones",
    //   LugarOrigen: "Iver Central",
    // },
    Directorio: "Secretario",
    RedAsignada: "Ruah",
    NivelLiderazgo: "Diacono",
    EquipoTrabajo: "Diaconos",
    GrupoAsignado: "Iver Varones",
    LugarOrigen: "Iver Central",
  },
  {
    id: 2,
    Rut: 17388935,
    Nombres: "Daniela Valeska",
    ApellidoMaterno: "Quevedo",
    ApellidoPaterno: "Navarro",
    FechaNacimiento: "1989-09-05",
    NumeroContacto: 978772331,
    EstadoCivil: "Casado",
    email: "michael.foster@example.com",
    role: "Co-Founder / CTO",
    EstadoIglesia: "Activo",
    EstadoActualizacion: "Actualizado",
    imageUrl:
      "https://images.unsplash.com/photo-1519244703995-f4e0f30006d5?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80",
    lastSeen: "✅",
    lastSeenDateTime: "2023-01-23T13:23Z",
    // InfoIglesia: {
    //   Directorio: "Secretario",
    //   RedAsignada: "Ruah",
    //   NivelLiderazgo: "Diacono",
    //   EquipoTrabajo: "Diaconos",
    //   GrupoAsignado: "Iver Varones",
    //   LugarOrigen: "Iver Central",
    // },
    Directorio: null,
    RedAsignada: "Ruah",
    NivelLiderazgo: "Diacono",
    EquipoTrabajo: "Diaconos",
    GrupoAsignado: "Iver Varones",
    LugarOrigen: "Iver Central",
  },
  {
    id: 3,
    Rut: 14456545,
    Nombres: "Roberto Carlos",
    ApellidoMaterno: "Astudillo",
    ApellidoPaterno: "Perez",
    FechaNacimiento: "11-12-1974",
    NumeroContacto: 74321328,
    EstadoCivil: "Casado",
    email: "michael.foster@example.com",
    role: "Co-Founder / CTO",
    EstadoIglesia: "Activo",
    EstadoActualizacion: "Actualizado",
    imageUrl:
      "https://images.unsplash.com/photo-1519244703995-f4e0f30006d5?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80",
    lastSeen: "✅",
    lastSeenDateTime: "2023-01-23T13:23Z",
    // InfoIglesia: {
    //   Directorio: "Secretario",
    //   RedAsignada: "Ruah",
    //   NivelLiderazgo: "Pastor Principal",
    //   EquipoTrabajo: "Pastores",
    //   GrupoAsignado: "Iver Varones",
    //   LugarOrigen: "Iver Central",
    // },
    Directorio: "Director",
    RedAsignada: "Ruah",
    NivelLiderazgo: "Pastores Principales",
    EquipoTrabajo: "Pastores",
    GrupoAsignado: "Iver Varones",
    LugarOrigen: "Iver Central",
  },
];

export default sampledata;
